service: dio-serverless-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:sa-east-1:398721024867:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertitem:
    handler: src/insertItem.handler
    events:
      - httpApi:
          path: /item
          method: post
  fetchitems:
    handler: src/fetchItems.handler
    events:
      - httpApi:
          path: /item
          method: get
  fetchitem:
    handler: src/fetchItem.handler
    events:
      - httpApi:
          path: /item/{id}
          method: get
  updateitem:
    handler: src/updateItem.handler
    events:
      - httpApi:
          path: /item/{id}
          method: put
  deleteitem:
    handler: src/deleteItem.handler
    events:
      - httpApi:
          path: /item/{id}
          method: delete


resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
